SIM_TIME = 100000
BUS_STOP_STANDING_TIME = 0.5
SHELTER_EVACUATION_TIME = 1
NUMBER_OF_LANE = 2
WAITING_TIME = 0
BUS_SPEED = 8.33
BUS_LENGTH = 12
BUS_CAPACITY = 50

SHELTER_INDEX_1 = 381
SHELTER_INDEX_2 = 382

STAT_FLEET = dict()
STAT_EVACUEE = dict()
DISPLAY = False
FLEET_DISPLAY = False
STAT_INTERVAL = 3600

NUMBER_OF_FLEET = 322
FLEET_DONE = 0



def get_shelter_index(a):
    assert(a == SHELTER_INDEX_1 or a == SHELTER_INDEX_2)
    return 0 if a == SHELTER_INDEX_1 else 1